nome = str(input('Digite seu nome completo: '))
print(nome.upper())
print(nome.lower())
print(len(nome.replace(' ', '')))
print(len(nome)- nome.count(' '))
print(nome.find(' '))
separa = nome.split()
print(separa)
print('{} e tem {} letras'.format(separa[0],nome.find(' ')))
print('O nome é: {} e tem {} letras'.format(separa[0], len(separa[0])))